[project]
name = "all-in-one"
version = "1.0.0"
description = "Jac client application: all-in-one"
entry-point = "main.jac"

[jacpack]
name = "all-in-one"
description = "Complete all-in-one example with authentication and UI components"

[serve]
base_route_app = "app"

[plugins.client]
# Vite bundler configuration (optional overrides)
# vite.plugins = []
# vite.build = {}

[plugins.client.app_meta_data]
title = "All-In-One"
icon = ".assets/burger.png"
author = "Jaseci"
# meta_color_scheme = "dark"

[plugins.client.vite]
plugins = ["tailwindcss()"]
lib_imports = ["import tailwindcss from '@tailwindcss/vite'"]

[plugins.client.assets]
custom_extensions = [".py", ".js"]

[dependencies.npm]
antd = "^6.0.0"
"jac-client-node" = "1.0.4"
recharts = "latest"
tailwindcss = "latest"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "1.0.0"
"@tailwindcss/vite" = "^4.1.17"

[environments.response.headers]
"Cross-Origin-Opener-Policy" = "same-origin"
"Cross-Origin-Embedder-Policy" = "require-corp"
